= Docker image: boekhoff/jekyll-asciidoc
:link-docker: https://www.docker.com/[Docker]
:link-dockerhub: https://hub.docker.com[DockerHub]
:link-jekyll: https://jekyllrb.com/[Jekyll]
:link-asciidoctor: http://asciidoctor.org/[AsciiDoctor]
:link-image: https://hub.docker.com/r/boekhoff/jekyll-asciidoc/[boekhoff/jekyll-asciidoc]

This Git repository contains Dockerfiles for automated builds of Docker images
that are hosted as {link-image} on {link-dockerhub}.

The images are equipped with software for creating static sites from Asciidoc
files using {link-jekyll} and {link-asciidoctor}.

== Tags (+ installed software)

The {link-image}-images are build upon Jekyll's official Docker image
(https://hub.docker.com/r/jekyll/jekyll/[jekyll/jekyll]).
Changes in the following DockerHub repositories trigger a new automatic build
of the images:

* https://hub.docker.com/r/asciidoctor/docker-asciidoctor/[asciidoctor/docker-asciidoctor]
* https://hub.docker.com/r/jekyll/jekyll/[jekyll/jekyll]

The tags used by {link-image} resemble the version of the installed
https://github.com/asciidoctor/jekyll-asciidoc[jekyll-asciidoc] release.

* `1.1.2`:
  https://rubygems.org/gems/asciidoctor/versions/1.5.4[AsciiDoctor 1.5.4],
  https://rubygems.org/gems/jekyll-asciidoc/versions/1.1.2[jekyll-asciidoc 1.1.2]
* `latest`: For latest versions see
  https://rubygems.org/gems/asciidoctor[AsciiDoctor]
  and https://rubygems.org/gems/jekyll-asciidoc[jekyll-asciidoc]


== Usage

The Docker images are hosted as {link-image} on {link-dockerhub}.
Thus, you can pull an images by using the following terminal command:

[source,]
.Command to pull the latest image from DockerHub.
----
docker pull boekhoff/jekyll-asciidoc
----
