# Build image upon Ruby's official Docker image.
# https://hub.docker.com/_/ruby/
FROM ruby:alpine

# Install:
RUN \
  # https://github.com/tmm1/pygments.rb
  gem install pygments.rb &&\
  # https://github.com/asciidoctor/jekyll-asciidoc
  gem install jekyll-asciidoc

