# Build image upon Jekyll's official Docker image.
# https://hub.docker.com/r/jekyll/jekyll/
# https://github.com/jekyll/docker
FROM jekyll/jekyll

# Install:
RUN \
  # https://github.com/tmm1/pygments.rb
  #gem install pygments.rb &&\
  # https://github.com/asciidoctor/jekyll-asciidoc
  gem install jekyll-asciidoc

